### ISSUE TITLE
Maple Syrup 0.1.2 Beta crashes the server on startup

### ISSUE THREAD

**Issue by Tenoen** [VonZeeple/MapleSyrup-1.12.2#5]
Version 0.1.2 Beta of Maple Syrup will almost instantly crash any server it's installed on. The server I was testing this on is a standard Minecraft Forge 2847 server, all fresh and clean. No other mods, no strange launch parameters, no special versions of Java, and all default settings.

Here's the full crash report which was generated.
https://hastebin.com/bofacajoqe.rb

But, the main section is this here:
```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/statemap/StateMapperBase
	at vonzeeple.maplesyrup.MapleSyrup.registerBlocks(MapleSyrup.java:154)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_5_MapleSyrup_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.statemap.StateMapperBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 12 more
Caused by: java.lang.NullPointerException
```
Now, I'm not very knowledgeable when it comes to Java, but from what I can tell it's attempting to call upon a client-side class which doesn't work proper on a server. I think it needs to have some server-side specific stuff in place of the client-side things it's attempting to pull from, but I'm unsure.

**Comment by VonZeeple** [comment]
I think this is a missing annotation in the block class. I'm fixing this asap.

**Comment by VonZeeple** [comment]
Fixed in latest version
